language: node_js
node_js:
  - "6.3.1"
script:
  - npm --version
  - npm install
after_success:
 - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then npm run deploy; rc=$?; elif [[ "$TRAVIS_BRANCH" == "release" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then npm run deploy:prod; rc=$?; fi; exit $rc;
# deploy:
#   - provider: script
#     name: prod-deploy
#     script: CF_DISTRIBUTION_ID=$PROD_CF_DISTRIBUTION_ID npm run deploy:prod
#     on:
#       branch: release

#   - provider: script
#     name: staging-deploy
#     script: CF_DISTRIBUTION_ID=$STAGING_CF_DISTRIBUTION_ID npm run deploy
#     on:
#       branch: master
