image: node:6.3.1
pipelines:
  branches:
    master:
      - step:
          script:
            - npm --version
            - npm install
            - bin/create_pipelines_env.sh
            - npm run deploy:prod
