image: node:6.3.1
pipelines:
  master:
    - step:
        script:
          - npm --version
          - npm install
          - bin/create_pipelines_env.sh
          - npm test
          - npm run deploy:prod