export const FETCH_ZAPIER_TOKEN_REQUEST = 'FETCH_ZAPIER_TOKEN_REQUEST';
export const FETCH_ZAPIER_TOKEN_SUCCESS = 'FETCH_ZAPIER_TOKEN_SUCCESS';
export const FETCH_ZAPIER_TOKEN_FAIL = 'FETCH_ZAPIER_TOKEN_FAIL';
export const UPDATE_SELECTED_PLATFORM = 'UPDATE_SELECTED_PLATFORM';

export const FETCH_WEBHOOKS_REQUEST = 'FETCH_WEBHOOKS_REQUEST';
export const FETCH_WEBHOOKS_SUCCESS = 'FETCH_WEBHOOKS_SUCCESS';
export const FETCH_WEBHOOKS_FAIL = 'FETCH_WEBHOOKS_FAIL';

export const CREATE_WEBHOOKS_REQUEST = 'CREATE_WEBHOOKS_REQUEST';
export const CREATE_WEBHOOKS_SUCCESS = 'CREATE_WEBHOOKS_SUCCESS';
export const CREATE_WEBHOOKS_FAIL = 'CREATE_WEBHOOKS_FAIL';

export const UPDATE_WEBHOOKS_REQUEST = 'UPDATE_WEBHOOKS_REQUEST';
export const UPDATE_WEBHOOKS_SUCCESS = 'UPDATE_WEBHOOKS_SUCCESS';
export const UPDATE_WEBHOOKS_FAIL = 'UPDATE_WEBHOOKS_FAIL';

export const DELETE_WEBHOOKS_REQUEST = 'DELETE_WEBHOOKS_REQUEST';
export const DELETE_WEBHOOKS_SUCCESS = 'DELETE_WEBHOOKS_SUCCESS';
export const DELETE_WEBHOOKS_FAIL = 'DELETE_WEBHOOKS_FAIL';