export const REQUEST_CUSTOMERS_FETCH = 'REQUEST_CUSTOMERS_FETCH';
export const FETCH_CUSTOMERS_REQUEST = 'FETCH_CUSTOMERS_REQUEST';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAIL = 'FETCH_CUSTOMERS_FAIL';
export const DELETE_CUSTOMER_START = 'DELETE_CUSTOMER_START';
export const DELETE_CUSTOMER_CANCEL = 'DELETE_CUSTOMER_CANCEL';
export const DELETE_CUSTOMER_REQUEST = 'DELETE_CUSTOMER_REQUEST';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAIL = 'DELETE_CUSTOMER_FAIL';
export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAIL = 'CREATE_CUSTOMER_FAIL';
export const DUPLICATE_CUSTOMER_REQUEST = 'DUPLICATE_CUSTOMER_REQUEST';
export const DUPLICATE_CUSTOMER_SUCCESS = 'DUPLICATE_CUSTOMER_SUCCESS';
export const DUPLICATE_CUSTOMER_FAIL = 'DUPLICATE_CUSTOMER_FAIL';

