export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const PHONE_VERIFICATION_START_REQUEST = 'PHONE_VERIFICATION_START_REQUEST';
export const PHONE_VERIFICATION_START_SUCCESS = 'PHONE_VERIFICATION_START_SUCCESS';
export const PHONE_VERIFICATION_START_FAIL = 'PHONE_VERIFICATION_START_FAIL';
export const PHONE_VERIFICATION_CHECK_REQUEST = 'PHONE_VERIFICATION_CHECK_REQUEST';
export const PHONE_VERIFICATION_CHECK_SUCCESS = 'PHONE_VERIFICATION_CHECK_SUCCESS';
export const PHONE_VERIFICATION_CHECK_FAIL = 'PHONE_VERIFICATION_CHECK_FAIL';
export const PHONE_VERIFICATION_CHECK_CANCEL = 'PHONE_VERIFICATION_CHECK_CANCEL';
export const PHONE_EDIT_START = 'PHONE_EDIT_START';
export const PHONE_EDIT_CANCEL = 'PHONE_EDIT_CANCEL';
