export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const UPDATE_PROFILE_METADATA_REQUEST = 'UPDATE_PROFILE_METADATA_REQUEST';
export const UPDATE_PROFILE_METADATA_SUCCESS = 'UPDATE_PROFILE_METADATA_SUCCESS';
export const UPDATE_PROFILE_METADATA_FAIL = 'UPDATE_PROFILE_METADATA_FAIL';

export const PHONE_VERIFICATION_START_REQUEST = 'PHONE_VERIFICATION_START_REQUEST';
export const PHONE_VERIFICATION_START_SUCCESS = 'PHONE_VERIFICATION_START_SUCCESS';
export const PHONE_VERIFICATION_START_FAIL = 'PHONE_VERIFICATION_START_FAIL';
export const PHONE_VERIFICATION_CHECK_REQUEST = 'PHONE_VERIFICATION_CHECK_REQUEST';
export const PHONE_VERIFICATION_CHECK_SUCCESS = 'PHONE_VERIFICATION_CHECK_SUCCESS';
export const PHONE_VERIFICATION_CHECK_FAIL = 'PHONE_VERIFICATION_CHECK_FAIL';
export const PHONE_VERIFICATION_CHECK_CANCEL = 'PHONE_VERIFICATION_CHECK_CANCEL';
export const PHONE_EDIT_START = 'PHONE_EDIT_START';
export const PHONE_EDIT_CANCEL = 'PHONE_EDIT_CANCEL';

export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_FAIL = 'FILE_UPLOAD_FAIL';
export const FILE_DELETE_START = 'FILE_DELETE_START';
export const FILE_DELETE_CANCEL = 'FILE_DELETE_CANCEL';
export const FILE_DELETE_REQUEST = 'FILE_DELETE_REQUEST';
export const FILE_DELETE_SUCCESS = 'FILE_DELETE_SUCCESS';
export const FILE_DELETE_FAIL = 'FILE_DELETE_FAIL';
export const FILE_URL_UPDATE = 'FILE_URL_UPDATE';

export const PROFILE_VERIFICATION_START = 'PROFILE_VERIFICATION_START';
export const PROFILE_VERIFICATION_CANCEL = 'PROFILE_VERIFICATION_CANCEL';
export const PROFILE_VERIFICATION_REQUEST = 'PROFILE_VERIFICATION_REQUEST';
export const PROFILE_VERIFICATION_SUCCESS = 'PROFILE_VERIFICATION_SUCCESS';
export const PROFILE_VERIFICATION_FAIL = 'PROFILE_VERIFICATION_FAIL';

