export const FETCH_C_TRANSACTIONS_REQUEST = 'FETCH_C_TRANSACTIONS_REQUEST';
export const FETCH_C_TRANSACTIONS_SUCCESS = 'FETCH_C_TRANSACTIONS_SUCCESS';
export const FETCH_C_TRANSACTIONS_FAIL = 'FETCH_C_TRANSACTIONS_FAIL';
export const CLEAR_C_TRANSACTIONS = 'CLEAR_C_TRANSACTIONS';
