export const FETCH_SUB_ACCOUNTS_REQUEST = 'FETCH_SUB_ACCOUNTS_REQUEST';
export const FETCH_SUB_ACCOUNTS_SUCCESS = 'FETCH_SUB_ACCOUNTS_SUCCESS';
export const FETCH_SUB_ACCOUNTS_FAIL = 'FETCH_SUB_ACCOUNTS_FAIL';
export const CLEAR_SUB_ACCOUNTS = 'CLEAR_SUB_ACCOUNTS';
