export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL';

export const PHONE_VERIFICATION_REQUEST = "PHONE_VERIFICATION_REQUEST";
export const PHONE_VERIFICATION_SUCCESS = "PHONE_VERIFICATION_SUCCESS";
export const PHONE_VERIFICATION_FAIL = "PHONE_VERIFICATION_FAIL";

export const PHONE_VERIFICATION_CHECK_START = "PHONE_VERIFICATION_CHECK_START";
export const PHONE_VERIFICATION_CHECK_STOP = "PHONE_VERIFICATION_CHECK_STOP";

export const PHONE_VERIFICATION_CHECK_REQUEST = "PHONE_VERIFICATION_CHECK_REQUEST";
export const PHONE_VERIFICATION_CHECK_SUCCESS = "PHONE_VERIFICATION_CHECK_SUCCESS";
export const PHONE_VERIFICATION_CHECK_FAIL = "PHONE_VERIFICATION_CHECK_FAIL";