export const FETCH_BANK_ACCOUNTS_REQUEST = 'FETCH_BANK_ACCOUNTS_REQUEST';
export const FETCH_BANK_ACCOUNTS_SUCCESS = 'FETCH_BANK_ACCOUNTS_SUCCESS';
export const FETCH_BANK_ACCOUNTS_FAIL = 'FETCH_BANK_ACCOUNTS_FAIL';

export const ADD_BANK_ACCOUNT_START = 'ADD_BANK_ACCOUNT_START';
export const ADD_BANK_ACCOUNT_REQUEST = 'ADD_BANK_ACCOUNT_REQUEST';
export const ADD_BANK_ACCOUNT_SUCCESS = 'ADD_BANK_ACCOUNT_SUCCESS';
export const ADD_BANK_ACCOUNT_FAIL = 'ADD_BANK_ACCOUNT_FAIL';
export const ADD_BANK_ACCOUNT_CANCEL = 'ADD_BANK_ACCOUNT_CANCEL';
