export const FETCH_BANK_ACCOUNTS_REQUEST = 'FETCH_BANK_ACCOUNTS_REQUEST';
export const FETCH_BANK_ACCOUNTS_SUCCESS = 'FETCH_BANK_ACCOUNTS_SUCCESS';
export const FETCH_BANK_ACCOUNTS_FAIL = 'FETCH_BANK_ACCOUNTS_FAIL';

export const SAVE_BANK_ACCOUNT_START = 'SAVE_BANK_ACCOUNT_START';
export const SAVE_BANK_ACCOUNT_REQUEST = 'SAVE_BANK_ACCOUNT_REQUEST';
export const SAVE_BANK_ACCOUNT_SUCCESS = 'SAVE_BANK_ACCOUNT_SUCCESS';
export const SAVE_BANK_ACCOUNT_FAIL = 'SAVE_BANK_ACCOUNT_FAIL';
export const SAVE_BANK_ACCOUNT_CANCEL = 'SAVE_BANK_ACCOUNT_CANCEL';

export const DELETE_BANK_ACCOUNT_START = 'DELETE_BANK_ACCOUNT_START';
export const DELETE_BANK_ACCOUNT_CANCEL = 'DELETE_BANK_ACCOUNT_CANCEL';
export const DELETE_BANK_ACCOUNT_REQUEST = 'DELETE_BANK_ACCOUNT_REQUEST';
export const DELETE_BANK_ACCOUNT_SUCCESS = 'DELETE_BANK_ACCOUNT_SUCCESS';
export const DELETE_BANK_ACCOUNT_FAIL = 'DELETE_BANK_ACCOUNT_FAIL';
