export const VERIFY_BANK_ACCOUNT_REQUEST = 'VERIFY_BANK_ACCOUNT_REQUEST';
export const VERIFY_BANK_ACCOUNT_SUCCESS = 'VERIFY_BANK_ACCOUNT_SUCCESS';
export const VERIFY_BANK_ACCOUNT_FAIL = 'VERIFY_BANK_ACCOUNT_FAIL';

export const ADD_BANK_ACCOUNT_START = 'ADD_BANK_ACCOUNT_START';
export const ADD_BANK_ACCOUNT_REQUEST = 'ADD_BANK_ACCOUNT_REQUEST';
export const ADD_BANK_ACCOUNT_SUCCESS = 'ADD_BANK_ACCOUNT_SUCCESS';
export const ADD_BANK_ACCOUNT_FAIL = 'ADD_BANK_ACCOUNT_FAIL';
export const ADD_BANK_ACCOUNT_CANCEL = 'ADD_BANK_ACCOUNT_CANCEL';
