export const UPDATE_SELECTED_PLATFORM = 'UPDATE_SELECTED_PLATFORM';

export const CREATE_ZAPIER_TOKEN_REQUEST = 'CREATE_ZAPIER_TOKEN_REQUEST';
export const CREATE_ZAPIER_TOKEN_SUCCESS = 'CREATE_ZAPIER_TOKEN_SUCCESS';
export const CREATE_ZAPIER_TOKEN_FAIL = 'CREATE_ZAPIER_TOKEN_FAIL';

export const UPDATE_SUB_ACCOUNT_REQUEST = 'UPDATE_SUB_ACCOUNT_REQUEST';
export const UPDATE_SUB_ACCOUNT_SUCCESS = 'UPDATE_SUB_ACCOUNT_SUCCESS';
export const UPDATE_SUB_ACCOUNT_FAIL = 'UPDATE_SUB_ACCOUNT_FAIL';
