export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const UPDATE_PROFILE_LOCALLY = 'UPDATE_PROFILE_LOCALLY';
export const INIT_PROFILE_SANDBOX = 'INIT_PROFILE_SANDBOX';
export const SET_PROFILE_SANDBOX = 'SET_PROFILE_SANDBOX';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';

export const VALIDATE_PROFILE = 'VALIDATE_PROFILE';
