export const FETCH_CHANNELS_REQUEST = 'FETCH_CHANNELS_REQUEST';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';
export const FETCH_CHANNELS_FAIL = 'FETCH_CHANNELS_FAIL';
export const CLEAR_CHANNELS = 'CLEAR_CHANNELS';
