export const FETCH_WEBHOOKS_REQUEST = 'FETCH_WEBHOOKS_REQUEST';
export const FETCH_WEBHOOKS_SUCCESS = 'FETCH_WEBHOOKS_SUCCESS';
export const FETCH_WEBHOOKS_FAIL = 'FETCH_WEBHOOKS_FAIL';

export const SAVE_WEBHOOK_START = 'SAVE_WEBHOOK_START';
export const SAVE_WEBHOOK_CANCEL = 'SAVE_WEBHOOK_CANCEL';
export const SAVE_WEBHOOK_REQUEST = 'SAVE_WEBHOOK_REQUEST';
export const SAVE_WEBHOOK_SUCCESS = 'SAVE_WEBHOOK_SUCCESS';
export const SAVE_WEBHOOK_FAIL = 'SAVE_WEBHOOK_FAIL';

export const DELETE_WEBHOOK_START = 'DELETE_WEBHOOK_START';
export const DELETE_WEBHOOK_CANCEL = 'DELETE_WEBHOOK_CANCEL';
export const DELETE_WEBHOOK_REQUEST = 'DELETE_WEBHOOK_REQUEST';
export const DELETE_WEBHOOK_SUCCESS = 'DELETE_WEBHOOK_SUCCESS';
export const DELETE_WEBHOOK_FAIL = 'DELETE_WEBHOOK_FAIL';
