export const REQUEST_DASHBOARD_FETCH = 'REQUEST_DASHBOARD_FETCH';
export const FETCH_DASHBOARD_REQUEST = 'FETCH_DASHBOARD_REQUEST';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const FETCH_DASHBOARD_FAIL = 'FETCH_DASHBOARD_FAIL';
export const DELETE_DASHBOARD_START = 'DELETE_DASHBOARD_START';
export const DELETE_DASHBOARD_CANCEL = 'DELETE_DASHBOARD_CANCEL';
export const DELETE_DASHBOARD_REQUEST = 'DELETE_DASHBOARD_REQUEST';
export const DELETE_DASHBOARD_SUCCESS = 'DELETE_DASHBOARD_SUCCESS';
export const DELETE_DASHBOARD_FAIL = 'DELETE_DASHBOARD_FAIL';
export const CREATE_DASHBOARD_REQUEST = 'CREATE_DASHBOARD_REQUEST';
export const CREATE_DASHBOARD_SUCCESS = 'CREATE_DASHBOARD_SUCCESS';
export const CREATE_DASHBOARD_FAIL = 'CREATE_DASHBOARD_FAIL';
export const DUPLICATE_DASHBOARD_REQUEST = 'DUPLICATE_DASHBOARD_REQUEST';
export const DUPLICATE_DASHBOARD_SUCCESS = 'DUPLICATE_DASHBOARD_SUCCESS';
export const DUPLICATE_DASHBOARD_FAIL = 'DUPLICATE_DASHBOARD_FAIL';

