export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAIL = 'FETCH_TRANSACTIONS_FAIL';
export const CLEAR_TRANSACTIONS = 'CLEAR_TRANSACTIONS';
export const VIEW_TRANSACTIONS_START = 'VIEW_TRANSACTIONS_START';
export const VIEW_TRANSACTIONS_CANCEL = 'VIEW_TRANSACTIONS_CANCEL';
export const EXPORT_TRANSACTIONS_START = 'EXPORT_TRANSACTIONS_START';
export const EXPORT_TRANSACTIONS_CANCEL = 'EXPORT_TRANSACTIONS_CANCEL';
