export const REQUEST_TRANSACTIONS_FETCH = 'REQUEST_TRANSACTIONS_FETCH';
export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAIL = 'FETCH_TRANSACTIONS_FAIL';
export const DELETE_TRANSACTION_START = 'DELETE_TRANSACTION_START';
export const DELETE_TRANSACTION_CANCEL = 'DELETE_TRANSACTION_CANCEL';
export const DELETE_TRANSACTION_REQUEST = 'DELETE_TRANSACTION_REQUEST';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAIL = 'DELETE_TRANSACTION_FAIL';
export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const CREATE_TRANSACTION_FAIL = 'CREATE_TRANSACTION_FAIL';
export const DUPLICATE_TRANSACTION_REQUEST = 'DUPLICATE_TRANSACTION_REQUEST';
export const DUPLICATE_TRANSACTION_SUCCESS = 'DUPLICATE_TRANSACTION_SUCCESS';
export const DUPLICATE_TRANSACTION_FAIL = 'DUPLICATE_TRANSACTION_FAIL';

